package io.github.dudmacedo.projecteuler.problemas;

public class Problema0002 implements Problema {

	Long resultado;

	@Override
	public String getTitulo() {
		return "Even Fibonacci numbers";
	}

	@Override
	public String getDescricao() {
		return "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\r\n"
				+ "\r\n" + "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\r\n" + "\r\n"
				+ "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.";
	}

	@Override
	public String getResultado() {
		return resultado.toString();
	}

	@Override
	public void run() {
		Long fib1 = 1L;
		Long fib2 = 1L;
		Long count = 1L;
		Long limite = 4000000L;
		Long soma = 0L;

		while (fib1 <= limite) {
			Long aux = fib2;
			fib2 = fib(fib1, fib2);
			fib1 = aux;
			if (fib1 % 2 == 0) {
				soma += fib1;
			}
			count++;
		}
		
		resultado = soma;

	}

	private Long fib(Long fib1, Long fib2) {
		return fib1 + fib2;
	}

}
